# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


Importar libreria Numpy

In [1]:
#Importar numpy
import numpy as np

1.Crear un arreglo de ceros de longitud 12

In [12]:
arreglo1= np.zeros(12)
print(arreglo1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y y un 10 en la posición número 5

In [13]:
arreglo2=np.zeros(10)
arreglo2[4]=10
print(arreglo2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49

In [17]:
arreglo3=np.array(range(10,50))
print(arreglo3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [18]:
arreglo4 = np.array(range(0,9)).reshape(3, 3) #con reshape digo de cuantas filas y columnas (respectivamente) quiero el arreglo
print(arreglo4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [29]:
arreglo5= np.random.randint(0,100,100) #primer posición valor mínimo aleatorio, segunda maximo, tercera tamaño de arreglo
print("Arreglo de numeros aleatorios del 1 al 100, de n=100")
print(arreglo5)

print("") #Para que no quede cada resultado pegado al anterior

print("Tamaño del arreglo:", arreglo5.size)

print("")

print("Media",np.mean(arreglo5))

print("")

print("Varianza", round(np.var(arreglo5),2)) #Con round selecciono los decimales, en este caso, 2

Arreglo de numeros aleatorios del 1 al 100, de n=100
[22 96 59 81 66 44 24 40 59 71 71 71 93 89 55 81 85 87 95 25 29 65 31 69
  1 30 26 82 80 58 45 93 57 63 52 45 41 81 34 19 32 65 92 85 64 82 25  5
 22 39 86 92 51 71 34 27 86 87 78 77 21 65 60 45 66 64 18 85 32 12 26 63
 85 12 86 57 68 80 90 22 64 83 91 56  3 23 74 96 51 75 63 36  6 15 87 58
 50 23 13 36]

Tamaño del arreglo: 100

Media 55.75

Varianza 711.57


6.Calcular la media de un arreglo usando np.sum


In [30]:

media=np.sum(arreglo5)/len(arreglo5)

print("Siendo que la suma del arreglo es:",(np.sum(arreglo5)), "y la longitud del arreglo es:",(len(arreglo5)))
print("La media de arreglo5 usando np.sum es:",(media))


Siendo que la suma del arreglo es: 5575 y la longitud del arreglo es: 100
La media de arreglo5 usando np.sum es: 55.75


7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [31]:
print("Varianza con np.var de arreglo5=",np.var(arreglo5))

varianza_arreglo5=np.sum((arreglo5-np.mean(arreglo5))**2)/len(arreglo5)  #varianza es sumatoria (xi-xmedia)^2 /n (n=100)

print("Varianza con np.sum y np.mean de arreglo5=",varianza_arreglo5)

Varianza con np.var de arreglo5= 711.5675
Varianza con np.sum y np.mean de arreglo5= 711.5675


8. Crear un array de números aleatorios usando np.random.randn.

In [34]:
arreglo8= np.random.randint(0,10,50)
print("Arreglo de numeros aleatorios del 1 al 10, de n=50")
print(arreglo8)

print("Tamaño del arreglo:", arreglo8.size)

Arreglo de numeros aleatorios del 1 al 10, de n=50
[9 6 1 6 6 1 0 3 4 3 0 6 3 0 2 0 5 7 9 3 3 9 9 3 2 2 3 8 0 5 7 8 6 4 5 5 3
 0 0 7 6 9 7 1 0 3 2 6 0 9]
Tamaño del arreglo: 50
